
jobs:
    - script: |
          pipelineJob('gen-ai-api') {
              description('CI/CD pipeline for gen-ai-api')
          
              definition {
                  cpsScm {
                      scm {
                          git {
                              remote {
                                  url('https://github.com/myc-public/gen-ai-api.git')
                              }
                              branches('*/main')
                          }
                      }
                      scriptPath('cicd/Jenkinsfile-ci')
                      lightweight(true)
                  }
              }

              properties {
                  disableConcurrentBuilds()
              }

              logRotator {
                  numToKeep(20)
                  daysToKeep(30)
              }
          }

    - script: |
          pipelineJob('inner-order-api') {
              description('CI/CD pipeline for inner-order-api')

              parameters {
                  choiceParam('BRANCH', ['develop', 'uat', 'preprod', 'main'], 'Git Branch to be used by the build')
              }
          
              definition {
                  cpsScm {
                      scm {
                          git {
                              remote {
                                  url('https://github.com/myc-public/inner-order-api.git')
                              }
                              branches('*/main')
                          }
                      }
                      scriptPath('cicd/Jenkinsfile-ci')
                      lightweight(true)
                  }
              }
          
              properties {
                  disableConcurrentBuilds()
              }
          
              logRotator {
                  numToKeep(20)
                  daysToKeep(30)
              }
          }

    - script: |
          pipelineJob('inner-donation-api') {
              description('CI/CD pipeline for inner-donation-api')

              parameters {
                  choiceParam('BRANCH', ['develop', 'uat', 'preprod', 'main'], 'Git Branch to be used by the build')
              }

              definition {
                  cpsScm {
                      scm {
                          git {
                              remote {
                                  url('https://github.com/myc-public/inner-donation-api.git')
                              }
                              branches('*/main')
                          }
                      }
                      scriptPath('cicd/Jenkinsfile-ci')
                      lightweight(true)
                  }
              }

              properties {
                  disableConcurrentBuilds()
              }

              logRotator {
                  numToKeep(20)
                  daysToKeep(30)
              }
          }