apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-m2-cache
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/component: maven-cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
