apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/agent: "true"

spec:
  serviceAccountName: jenkins

  volumes:
    - name: jenkins-home
      emptyDir: {}

  containers:
    - name: maven
      image: maven:3.9.11-eclipse-temurin-21

      command:
        - sleep

      args:
        - "99d"

      tty: true

      env:
        - name: HOME
          value: /home/jenkins

        - name: MAVEN_CONFIG
          value: /home/jenkins/.m2

      volumeMounts:
        - name: jenkins-home
          mountPath: /home/jenkins

      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"

        limits:
          cpu: "1"
          memory: "2Gi"