apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  labels:
    app.kubernetes.io/name: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi