pipeline {
    agent {
        kubernetes {
            cloud 'openshift'
            yamlFile 'agents/java/pod-template.yaml'
            agentContainer 'maven'
            agentInjection true
        }
    }

    options {
        timestamps()
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {
        stage('Agent Test') {
            steps {
                sh 'java -version'
                sh 'mvn -version'
                sh 'echo "Jenkins ephemeral agent OK"'
            }
        }

        stage('SonarCloud Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                            -Dsonar.organization=myc-public \
                            -Dsonar.projectKey=myc-public_donation-api
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}